name: mmtf-genomics

channels:
  - conda-forge
  - anaconda

dependencies:
  - python=3.7
  - openjdk=8.0.152
  - pyspark=2.4.0
  - py4j=0.10.7
  - biopython=1.72
  - numba=0.49.0
  - jupyterlab=3
  - ipywidgets=7.6.2
  - py2neo
  - monotonic
  - pip
  - pip:
    - git+https://github.com/sbl-sdsc/mmtf-pyspark.git 
    - rcsbsearch==0.2.1
